### ISSUE TITLE
nethserver-glances install breaks letsencrypt

### ISSUE THREAD

**Issue by ghost** [stephdl/dev#7]
Upon installing nethserver-glances, letsencrypt cert renewal is broken. Removal of the package followed by a cleanup with autoremove does not fix the issue.
`
[root@server ~]# /usr/libexec/nethserver/letsencrypt-certs -v
`
results in...
`
Traceback (most recent call last):
File "/usr/bin/certbot", line 9, in <module>
load_entry_point('certbot==0.24.0', 'console_scripts', 'certbot')()
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
return ep.load()
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
return self.resolve()
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/usr/lib/python2.7/site-packages/certbot/main.py", line 20, in <module>
from certbot import client
File "/usr/lib/python2.7/site-packages/certbot/client.py", line 13, in <module>
from acme import client as acme_client
File "/usr/lib/python2.7/site-packages/acme/client.py", line 36, in <module>
urllib3.contrib.pyopenssl.inject_into_urllib3()
File "/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 112, in inject_into_urllib3
_validate_dependencies_met()
File "/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 147, in _validate_dependencies_met
raise ImportError("'pyOpenSSL' module missing required functionality. "
ImportError: 'pyOpenSSL' module missing required functionality. Try upgrading to v0.14 or newer.
`

I'm assuming pip installs some new and/or upgraded dependencies during the glances install, just not sure what could be causing the issue. 

I can also confirm it was 100% working before the glances install. I had the same thing happen to me before, and have slowly been reinstalling to track down what install was breaking it. The command ran fine before nethserver-glances was installed.

Latest NS7, fully updated, no extra repos except for yours to install glances.

**Comment by ghost** [comment]
I have tracked this down. The package was python-urllib3. It gets updated during the glances install and breaks letsencrypt.

I had to install python2-pip (removed during nethserver-glances cleanup), do a "pip unninstall urllib3", then a "yum reinstall urllib3" to fix the issue. Then I was able get letsencrypt to work just fine.

The pip package sets a immutable flag inside the package, a simple "yum reinstall urllib3" would not fix it without removing the package with pip first.
